name: CSS Lint
on:
  pull_request:
    branches:
      - "development"
    paths:
      - "**.scss"
      - "**.css"
      - "!dist/**"
  workflow_dispatch:
jobs:
  run-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install
        run: npm ci

      - name: Run CSS lint
        run: npm run lint:css
