name: JavaScript Lint and Unit Tests
on:
  pull_request:
    branches:
      - "development"
    paths:
      - "**.js"
      - "!dist/**"
  workflow_dispatch:
jobs:
  run-js:
    permissions:
      contents: read # Required to read the repository contents and do linting/testing
      pull-requests: read # Required to read pull request information (use write if you need to post the results on PRs)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22.17
          cache: npm

      - name: Install
        run: npm ci

      - name: Run JS lint
        run: npm run lint:js

      - name: Run JS unit tests
        run: npm run test

      - name: Run JS e2e tests
        run: npm run test:e2e