name: PHP Lint and Unit Tests
on:
  pull_request:
    branches:
      - "development"
    paths:
      - "**.php"
jobs:
  run-php-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP environment
        uses: php-actions/composer@v6 

      - name: Install
        run: composer install

      - name: Run phpcs
        run: composer run phpcs
      
      - name: Run phpunit
        run: composer run test
